### ISSUE TITLE
Consider renaming artifactIds

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-m2e-configurator#2]
The Maven coordinates for this project are a bit weird. They have embedded the groupId in them, and do not indicate that they are an m2e configurator. The artifactIds should probably be renamed.

I do not know the impact this would have on the resulting Eclipse artifacts, or what the normal naming conventions are for an m2e configurator or Eclipse plugin/feature. Even if there are restrictions or conventions which need to be followed for the Eclipse artifacts, it seems like it should still be possible, with some clever Maven trickery to use better Maven coordinates.

**Comment by hazendaz** [comment]
This is normal naming with m2e.  See https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/com.basistech.m2e.code.quality.checkstyle.feature/pom.xml.

What is incorrect are the folder names and unnecessary nesting.  I'm fixing that now.

**Comment by hazendaz** [comment]
Another example, shows same thing -> https://github.com/mybatis/generator/tree/master/eclipse
